### ISSUE TITLE
Corrected error numbers

### ISSUE THREAD

**Issue by jgharston** [mincebert/ecoxfer#2]
Not sure why, but my pull request diff is showing as every single line changed!

**Comment by mincebert** [comment]
Line ending characters — I use macOS/Unix so just have \n.

**Comment by jgharston** [comment]
On 04-03-2022 23:33, Robert Franklin wrote:
> Line ending characters — I use macOS/Unix so just have \n.

Ah, when I did SaveAs from GIT it must has saved with DOS line
endings as I was using Windows. And then I didn't notice any
problem Execing it into BASIC as the <CR><LF> works as the <LF>
just gets ignored, and the <CR> are, well, <CR>s. ;)

I've got an EOL utility that I should run on the file before
uploding it.

-- 
J.G.Harston - ***@***.*** - mdfs.net/jgh

**Comment by jgharston** [comment]
Sorted. A quick EOL -lf and the diff is much more sane, just showing the actual diffs. :)

**Comment by mincebert** [comment]
Thanks.  I'd already fixed it by just loading it into vim and changing the line ending character.

I've squashed the two commits into one so the change just shows what you did and we miss out the stage with the other line ending characters.  These are in v1.01.
